### ISSUE TITLE
Add per profile / command lockfile

### ISSUE THREAD

**Issue by renard** [creativeprojects/resticprofile#1]
Hi,

What about having per profile lock files to prevent from running the same job twice?

Even if restic already have such features it would be nice to prevent from launching several times the same tasks.

If a such option exists simply honour he lock file of skip it (allow to run job several times) if it does not.

Maybe having several configuration keys such as:

```
[profile.backup]
lockfile = /tmp/resticprofile-profile-backup.lock
```
This makes automated tasks safe.

Thanks in avance.

**Comment by creativeprojects** [comment]
Hi,

Yes that's something that should be quite easy to setup. And also a new command to reset a lock file if needed (like restic does)

(Sorry for my late answer, I was on holidays...)

**Comment by creativeprojects** [comment]
`lock` option has been added in version 0.6.0, but on the whole profile (not just on the `backup`)

I will release the new version in the next few days
