### ISSUE TITLE
check-before and --dry-run

### ISSUE THREAD

**Issue by tj57** [creativeprojects/resticprofile#100]
Restic 0.13.0 new option --dry-run has conflict with check-before: true.
Enhancement https://github.com/restic/restic/issues/1542: Add --dry-run/-n option to backup command

With this config:
``etc:
    initialize: false
    inherit: default
    backup:
        source: 
        - /etc/
        tag:
        - "etc"
        check-before: true`

command: resticprofile -v -n etc backup --dry-run -v got error unknown flag: --dry-run.
Without check-before works correctly.

**Comment by jkellerer** [comment]
Was too quick in closing. Should be closed when a new build is released and you verified it.
