### ISSUE TITLE
Remote syslog

### ISSUE THREAD

**Issue by bdillahu** [creativeprojects/resticprofile#105]
Maybe I'm missing the obvious way of doing it, but any thoughts of supporting logging to a remote syslog server in addition to the log file methods?

**Comment by creativeprojects** [comment]
Yeah I can add that on my list. That's easy enough to implement (I've done it before).

**Comment by creativeprojects** [comment]
Do you just want the resticprofile logs sent to syslog right?

There's no need to capture the restic output to send to syslog as well?

**Comment by bdillahu** [comment]
Correct, just the resticprofile logs were my thought...
