### ISSUE TITLE
launchd and sleeping machine

### ISSUE THREAD

**Issue by bdillahu** [creativeprojects/resticprofile#106]
This is probably handled already, but I'm not sure how to track it down - if my (Mac) is asleep when the scheduled job runs, does it run when the machine wakes up?

Apparently (https://developer.apple.com/forums/thread/52369) if you use the StartCalendarInterval then it will, otherwise it will  not. Depending on how this works, you could wind up with your machine never backing up (it's always asleep at the scheduled tiime)...

Sorry if that's obvious - I had a hand written script that I ran from cron checking for last run time to cover this, but your script is so, so, so much better, I want to use it instead :-)

**Comment by creativeprojects** [comment]
I only had scheduled jobs running when my Mac was switched on, and to be honest I never checked if they were running first thing after booting up. I should set them up again on my new Mac and see.

Anyway, I do use `StartCalendarInterval` so it should work properly 🤞🏻

**Comment by bdillahu** [comment]
Some quick testing shows it does seem to run as soon as it wakes up...

I had an hourly backup scheduled. Just before the hour I 1) made sure no restic processes were running and 2) confirmed with 'resticprofile status' that the next top of hour was when the job should run. I put the machine to sleep and waited until about 10 minutes after the hour. Woke it up and by the time I could type in the 'ps -ef' command, restic was running the scheduled backup. The resticprofile log shows the backup starting at 16:09... (when I woke it up).

So... seems good to me.

**Comment by creativeprojects** [comment]
Excellent, thank you for the investigation 👍🏻
