### ISSUE TITLE
Dedicated command "generate"

### ISSUE THREAD

**Issue by jkellerer** [creativeprojects/resticprofile#109]
There are more and more things coming that generate something. In milestone 0.17.0 it is `completion-script` and the long existed `random-key`, in 0.18.0 it will be JSON schema and config file reference.

Would it make sense to use a single `generate` command to cover the different cases (like `restic` does it)?

If we implement this for 0.17.0 then we'd only have to hide and deprecate command `random-key`. If we'd wait for next milestone we'd have 2 old commands to deprecate.

**Comment by creativeprojects** [comment]
yeah you're right, we should keep the commands similar to the restic ones, and it makes sense to do it now 👍🏻

**Comment by jkellerer** [comment]
Ok. Will take care of it later today.
