### ISSUE TITLE
Windows variables

### ISSUE THREAD

**Issue by tj57** [creativeprojects/resticprofile#111]
This command:

`    run-after-fail:`
`     - "curl -fsS --retry 3 --data-raw \"$ERROR_STDERR\" https://healthchecks.mydomain/ping/4b2fef02-0ccf-ff/$ERROR_EXIT_CODE"  `

works correcly under linux, but with windows not.
I tested $ERROR_STDERR, $ERROR_EXIT_CODE, %errorlevel%

Can variables in windows be the same as in linux ?

**Comment by jkellerer** [comment]
resticprofile uses a shell to execute commands, therefore the commands follow the syntax of the native shell. 

In Windows env variables are referenced with `% ERROR_EXIT_CODE%` when the default shell (cmd.exe) is used. 

With Power Shell the variable syntax would be `$Env:ERROR_EXIT_CODE`.

**Comment by tj57** [comment]
%ERROR_EXIT_CODE% works correclty, but %ERROR_STDERR% not.
Whether resticprofile can set the same variables on both systems ?

**Comment by jkellerer** [comment]
The variables are the same but the way how they are handled may differ depending on the shell. E. g. I’m not sure if cmd.exe would tolerate variable values with newlines (like in stderr).

**Comment by jkellerer** [comment]
While testing #112, I found on windows default shell (cmd.exe), double quotes are not properly escaped. You may have better results with single quotes instead. E.g.:
`"curl -fsS --retry 3 --data-raw '%ERROR_STDERR%' https://healthchecks.mydomain/ping/4b2fef02-0ccf-ff/%ERROR_EXIT_CODE%"`

But also in this case multiline is an issue. Starting a small script (that also has access to env variables) may fix this.

**Comment by tj57** [comment]
Great, thank you for your time and effort.

**Comment by creativeprojects** [comment]
Fixed in v0.18.0 (https://github.com/creativeprojects/resticprofile/releases/tag/v0.18.0)
