### ISSUE TITLE
profiles in exe dir ?

### ISSUE THREAD

**Issue by tj57** [creativeprojects/resticprofile#118]
I would like to suggest adding one more location for the profiles file: in the resticprofile.exe directory. This might be the last location to check.
This would be helpful when using resticprofile in portable mode, especially on Windows
Current directory is not sufficient when resticprofile is used in portable mode and you add this directory to the PATH variable

**Comment by creativeprojects** [comment]
I see what you mean. That's not a typical way of organising your files in a Unix fashion, but it is quite common in Windows.

Would another variable work? something like `.ProgramDir`, `.BinaryDir`, `.ResticProfileDir`?

Otherwise I'll add the .exe path to the search list (or I can do both)

**Comment by tj57** [comment]
Other variables do not work.
It will be usefull feature for Windows users.
Please consider adding this path
