### ISSUE TITLE
Support for max. number of connections

### ISSUE THREAD

**Issue by davosian** [creativeprojects/resticprofile#13]
Some back-up targets accept a configurable number of connections as explained here: https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#backblaze-b2. 

With restic you can change the default by passing along a `connections` parameter:

For Backblaze B2, it is `-o b2.connections=10`
For Microsoft Azure, it is `-o azure.connections=10`
For Google Cloud, it is `-o gs.connections=10`

Since the argument consists of 3 parts, I cannot find in the documentation nor in the samples how to add them in resticprofile. Is this possible or can it be added?

**Comment by creativeprojects** [comment]
Yes it is possible, using the long format of the flag: **option**

I just tried it with my Azure backup:

```ini
[azure]
repository = "azure:restic:/"
password-file = "azure-key"
option = "azure.connections=3"
```

and when running resticprofile, the right option gets generated:

```
$ resticprofile -n azure -v snapshots
2020/10/13 11:07:33 resticprofile 0.9.0 compiled with go1.14.6
2020/10/13 11:07:33 using configuration file: profiles.conf
2020/10/13 11:07:33 profile 'azure': starting 'snapshots'
2020/10/13 11:07:33 setting up environment variable 'AZURE_ACCOUNT_KEY'
2020/10/13 11:07:33 setting up environment variable 'AZURE_ACCOUNT_NAME'
2020/10/13 11:07:33 starting command: /opt/local/bin/restic snapshots --host vps --option azure.connections=3 --password-file azure-key --repo azure:restic:/ --verbose
```

**Comment by davosian** [comment]
This is great to know, thank you! Maybe it would help to either add this info to the README or to add this option to the Azure sample code?

I am getting ready for my second laptop to leverage resticprofile. 3 more to go, all different OS :)
