### ISSUE TITLE
Add rclone to the docker image

### ISSUE THREAD

**Issue by toast003** [creativeprojects/resticprofile#131]
I recently stumbled across resticprofile, and while it is almost perfect, I want back up my server's docker volumes to google drive, and having rclone on the resticprofile image would be quite nice, since that way you don't have to have another container running just so that you can back up stuff to the cloud.

In my case it's not _that_ big of a deal since [I need to change the entrypoint of the image anyways](https://github.com/creativeprojects/resticprofile/issues/74#issuecomment-1108868426), so I can just add a command to install it, but I imagine that other people could use it

**Comment by creativeprojects** [comment]
Yes I suppose I can add `rclone` in the future images, that makes sense 😛

**Comment by creativeprojects** [comment]
Now available in v0.18.0 (https://github.com/creativeprojects/resticprofile/releases/tag/v0.18.0)
