### ISSUE TITLE
Support of restic v0.14 with new repo format and compression

### ISSUE THREAD

**Issue by frabe1579** [creativeprojects/resticprofile#137]
Hello everybody.
Is there any change to implement for supporting restic v0.14 and its new big feature "Compression"?
I think nothing special for daily usage, but maybe something new is needed to support at least repo migration.
I don't know ***go*** so I cannot help.

**Comment by creativeprojects** [comment]
I've installed version 0.14.0, converted my repositories, and I haven't had any issue so far.

The only issue I can see for now, is the use of the now deprecated `--repo2` flag but I think it's still supported for now

**Comment by frabe1579** [comment]
I confirm, after some tests, no changes are needed.
I've run `resticprofile migrate upgrade_repo_v2 ` and then `resticprofile prune` to some of my repos with success, without using `--repo2`.
