### ISSUE TITLE
Write PID to lockfile

### ISSUE THREAD

**Issue by chrisb86** [creativeprojects/resticprofile#14]
I discovered restic a few weeks ago and startet to write my own wrapper script in POSIX shell.

Then I discovered resticprofile and realized that it implements all I've allready built or wanted to (and in a nicer way). I love it. Thanks for this nice project.

In my opinionen the profile specific lock files are really usefull and I've implemented them too. One thing that a miss in resticprofile ist the usage of the PID in lock files.

It happend a few times now that I had to kill the restic process or needed to restart the server while it was doing backups and the lockfiles remained. My cron jobs didn't run because resticprofile find the lockfiles and nothing happend until I deleted them manually. I know that the in the sample config the lockfiles are stored in /tmp. I think that's the wrong location for this kind of stuff and also helps when restarting the server.

I think it would be really helpfull to write the PID file of the given restic instance to the lock file too (or create an ordinary PID file at the os specific location and check if the PID is still in use at loading a profile. If it isn't restic can be called and the new PID should be stored in the PID file or lock file.

I don't know go but could provide my few lines of shell script that did the job for me until i switched to resticprofile.

**Comment by creativeprojects** [comment]
Hi,

I think I can easily add a PID inside the lock file. For now it contains the user, date time and the hostname (in case you use a shared drive).

So I could add the PID at the beginning of the file and check the process still exists.

I'll add a flag in the configuration as well to activate this new behaviour: It's possible someone using resticprofile would be surprised by this new automatic feature 😄

**Comment by creativeprojects** [comment]
will be available on version 0.9.2 👍🏻

**Comment by chrisb86** [comment]
👍🏻 Thanks :)
