### ISSUE TITLE
restic v0.14 - copy: replace --repo2 with --from-repo

### ISSUE THREAD

**Issue by tj57** [creativeprojects/resticprofile#142]
Resic v0.14 changed copy command in PR [#3742](https://github.com/restic/restic/pull/3742/commits/2758d76b77ba64372ce6d3ab2f2766a20cedad71)

"The old parameters names have been deprecated but still work"

**Comment by jkellerer** [comment]
Thanks a lot for the note. 

We have an ongoing pr #107 that will allow to perform versioning on restic flags when done. In the meantime we can rely on restic still accepting the current flags.

**Comment by creativeprojects** [comment]
Fixed in v0.21.0 👍🏻
