### ISSUE TITLE
Wildcard path expansion leads to excludes turning into additional source paths

### ISSUE THREAD

**Issue by kppullin** [creativeprojects/resticprofile#15]
### Problem Description

I have a `backup` config section using `iexclude` and ran into an issue where wildcard paths are expanded and lead to what should be excluded paths turning into additional backup paths.

Example config:
`iexclude = ["bin", "src/**/node_modules", "go/pkg"]`

When resticprofile runs it builds up this command to invoke restic: `sh -c  restic backup --iexclude bin --iexclude src/**/node_modules --iexclude go/pkg  --tag home /home/kevin`

So far so good.  However, when this command is shelled out and executed, the wildcards are expanded by `sh` into this command: `restic backup --iexclude bin --iexclude src/app1/node_modules src/app2/node_modules src/appN/node_modules --iexclude go/pkg <remaining args> <source_path>`

Note that the expanded paths following first found path (`src/app1/node_modules`) are NOT preceded by `--iexclude`.  This causes restic to treat `src/app2/node_modules`, etc as additional sources to include in the backup:

```
ID        Time                 Host        Tags        Paths
------------------------------------------------------------------------------------------------------------------------------
ffc66e1f  2020-09-06 09:04:35  desktop     home        /home/kevin
                                                       /home/kevin/src/app2/node_modules
<SNIP>
```

### Workaround and Possible Solutions

To workaround this, you can escape the `*` chars in the config so that `sh` does not expand them itself and lets restic handle globbing: `"src/\\*\\*/node_modules"`

A couple ideas to fix this:
- Automatically escape the `*` chars, similar to how other paths are handled via `fixPath` (I note that `iexclude` and the like fall into the `OtherFlags` list and are not "well known" as paths in the current code, so these may need to be made into "first class" config keys and handled as paths).
- Make a note in the docs that this escaping is necessary.
- [insert your better idea here]

**Comment by creativeprojects** [comment]
Hi,
Thanks for reporting this. I can definitely reproduce it.

Automatically escape the `*` sounds like the way to go.
I'm trying to think if there's any reason why sometimes we would **not** want it to be automatically escaped 🤔 

Also you're right, I should probably promote exclude and iexclude to fixPath. Good point 👍🏻

**Comment by fjarlq** [comment]
I think this bug still exists for the `resticprofile restore --include` option, for example:

```
$ resticprofile --name example-profile restore --verify --target /tmp/test --include '/Users/john/tmp/**/*.pl' 7d529a15
...
Fatal: more than one snapshot ID specified: [/Users/john/tmp/somedir/script.pl /Users/john/tmp/otherdir/junk.pl 7d529a15]
2025/10/11 15:56:08 restore on profile 'example-profile': exit status 1
```
