### ISSUE TITLE
Add 'target' flag to 'restore' command

### ISSUE THREAD

**Issue by ozboss** [creativeprojects/resticprofile#152]
Please add a 'target' flag to the 'restore' command. Together with #151 this would allow to restore for example some application data by simply calling `resticprofile application.restore latest` to restore the latest backup of the application.

**Comment by ozboss** [comment]
Yes it works, thanks for letting me know. I guess it should be added to the 'Flags passed to the restic command line' section in the reference documentation.

**Comment by jkellerer** [comment]
New reference is online with 0.21
