### ISSUE TITLE
Add tzdata package to docker image

### ISSUE THREAD

**Issue by KreativeKrise** [creativeprojects/resticprofile#159]
Please add the package tzdata to your Dockerfile to let the user change the timezone.
This would be useful if you want to run crond inside Docker and to get correct time in the log files.

Example:
```
FROM alpine:latest
RUN apk add --no-cache tzdata
ENV TZ=Etc/UTC
```

**Comment by creativeprojects** [comment]
Hey!

I'm reviewing the Docker image build so I'll see to include tzdata at the same time 👍🏻
