### ISSUE TITLE
go mod vendor fails with pulling internal modules

### ISSUE THREAD

**Issue by darix** [creativeprojects/resticprofile#163]
```
go mod vendor
github.com/creativeprojects/resticprofile tested by
	github.com/creativeprojects/resticprofile.test imports
	github.com/creativeprojects/resticprofile/mocks: no required module provides package github.com/creativeprojects/resticprofile/mocks; to add it:
	go get github.com/creativeprojects/resticprofile/mocks
```

**Comment by jkellerer** [comment]
The missing module is generate with `make mocks` (or `make all` if `mockery` does not exist).

However I guess it would be better to have mocks generated with `go generate` to not depend on a makefile for a basic build (and vendoring). Still I think `go mod vendor` would require a run of `go generate ./...`.

@creativeprojects , what do you think, should we create mocks with `go generate` instead? (had added a few more mocks in #107 , so could take care of the change)

**Comment by creativeprojects** [comment]
Yes sure, it's more _standard_ to use `go generate`. That's what I normally use anyway (not sure why I didn't put it there?)

**Comment by darix** [comment]
so that would mean in the vendor tarball for resticprofile I would need to also include the mocks directory or rerun the mocks step during the package build? (currently working on an opensuse package)

our workflow is:

1. generate vendor.tar.xz to have all the needed dependencies
2. build in a non networked environment.

**Comment by creativeprojects** [comment]
Well in theory vendoring shouldn't need the mocks package. You don't need it for building, only for running the unit tests. I'm not very familiar with vendoring (I've only used modules) so I'll have a look if the mocks package is badly declared or something

**Comment by darix** [comment]
just call `go mod vendor` in a working copy without generated mocks to reproduce it.

**Comment by creativeprojects** [comment]
I see, as per documentation:

> The go mod vendor command constructs a directory named vendor in the [main module’s](https://go.dev/ref/mod#glos-main-module) root directory that contains copies of all packages needed to support builds and tests of packages in the main module. Packages that are only imported by tests of packages outside the main module are not included.

So it does need the mocks to be able to run the tests in the imported module (_main module_ being resticprofile)

You will need to generate the mocks before you call `go mod vendor` in that case:
For now, can you run `make mocks` before `go mod vendor`?

Changing the repository to use `go generate` wouldn't necessarily make things simplier because you would still need to install the mock generator yourself.

I'm thinking, maybe the CI build could also generate a zip of `go mod vendor` ready to download for each version.

**Comment by darix** [comment]
sure can do. though i wonder why couldnt they be checked into git?

**Comment by creativeprojects** [comment]
These mocks are generated from an interface by a tool. It is a fairly common practice to check into source control only the files you wrote manually, but not the ones generated from a tool.

Sure you can check them in, some teams do in fact.

**Comment by darix** [comment]
my thinking was along the lines ... how often do the generated files change? usually just when you change the manually written files. so why not update both in step.
