### ISSUE TITLE
Cannot pass `--verbose=2` to restic

### ISSUE THREAD

**Issue by fetzerch** [creativeprojects/resticprofile#166]
I'd like to pass either [`--verbose --verbose` or `--verbose=2`](https://restic.readthedocs.io/en/latest/040_backup.html?highlight=verbose%3D2#backing-up) to restic so that it would print the status of all files.

While the documentation of [resticprofile](https://github.com/creativeprojects/resticprofile/blob/419e66c127d088d10d21df20642ff9f39cb45d97/docs/content/configuration/reference/index.md?plain=1#L83) states the type as `true/false OR int` I couldn't get it to work unfortunately. My configuration is:

```
...
default:
  verbose: 2
...
```

but that just passes `--verbose` to restic. I tried to workaround the issue by setting `v: 2` or `verbose: '2'`, but that just leads to parsing errors.

Does anyone have an idea how to get it to work?

In addition I think some of the examples in the documentation are not correct. The [reference](https://github.com/creativeprojects/resticprofile/blob/419e66c127d088d10d21df20642ff9f39cb45d97/docs/content/configuration/reference/index.md?plain=1#L83) mentions that `verbose` is an option for a profile. But [the examples](https://github.com/creativeprojects/resticprofile/blob/6ec92e5973cd0d2101db553f60549db9f51fbb56/docs/content/configuration/_index.md) mention it as part of the `backup` section. I tried this as well, but here `--verbose` is not passed to restic at all.

**Comment by jkellerer** [comment]
Will be addressed with #107 (the PR will provide a new reference and fix support for verbosity levels)

**Comment by creativeprojects** [comment]
Fixed in v0.21.0 👍🏻
