### ISSUE TITLE
Adding [additional flags] to the scheduled task

### ISSUE THREAD

**Issue by Schroedingers-Cat** [creativeprojects/resticprofile#167]
On Windows, it's important to run restich with the `--use-fs-snapshot` flag, as processes owning a file will block restic from reading that file. The flag invokes a shadow copy of the drive, allowing restic to read the data in a consistent state regardless of a file's access status.  

With resticprofile, it doesn't seem to be possible to store this flag in a profile. The only way I got this to work is by adding this flag via resticprofile's `additional flags` as part of the invocation (https://creativeprojects.github.io/resticprofile/usage/index.html#command-line-reference).  

This impacts the ergonomics of using resticprofile for scheduling tasks, as users have to go to Windows' task scheduler UI and manipulate all generated tasks to postfix the additional `--use-fs-snapshot` flag.  

It would be great if there was a way to store the additional restic flags invoked with a backup task directly in the profile, so that a manipulation of the generated task isn't necessary. While this use case is specific to Windows, there might be other use cases that benefit from having additional flags stored in the profile.

**Comment by jkellerer** [comment]
Hi @Schroedingers-Cat, had you tried, the following already?

```yaml
default:
  backup:
    use-fs-snapshot: true
```

Also could you share part of the configuration containing `use-fs-snapshot` and run `resticprofile --dry-run yourprofile.backup` and post the output here. Thanks!

**Comment by Schroedingers-Cat** [comment]
This is working, indeed. I didn't find this in the documentation so I assumed it was supported only via restic's additional flags.

Thanks a lot!  

Maybe you could add this to the  docs in the `[profile.backup]` section below `Flags passed to the restic command line`? https://creativeprojects.github.io/resticprofile/configuration/reference/index.html#profile-sections

**Comment by jkellerer** [comment]
An all new (generated) reference is in the making and will be released soon with #107

**Comment by jkellerer** [comment]
New reference is available with 0.21
