### ISSUE TITLE
Systemd: Type=oneshot may create multiple invocations of one profile

### ISSUE THREAD

**Issue by jkellerer** [creativeprojects/resticprofile#17]
Thanks a lot for the great work, it really helps to make restic easy to use.

**Discovered issue:**
When using relatively short schedules (systemd), I've discovered that when a backup takes longer than the configured schedule interval, another concurrent resticprofile process is started by the same timer & profile which either causes unnecessary load or errors.

(Note: lock file doesn't help in its current implementation as it has other side effects like schedules never run and/or producing lock errors in syslog)

**Expected:**
A systemd timer activates a resticprofile service on schedule if not already running but does not active multiple instances of the same service.

**Reason:**
Based on the following references this is the expected behaviour for service `Type=oneshot` since in this type a service never reaches `active` state and therefore a timer is always triggering a new service start even if the previous service is still running.

* https://unix.stackexchange.com/questions/203254/does-systemd-timer-unit-skip-the-next-run-if-the-process-hasnt-finished-yet
* https://www.freedesktop.org/software/systemd/man/systemd.service.html#Options

Could we change the type to `exec` or `simple` instead, so that a running service is in state `active` and a timer will not trigger another run while the service is in this state?

My understanding of `oneshot` is that it is meant for short-lived services that must have fully executed when someone depends on them, therefore invocation blocks (in state `activating`) while the service runs (can be seen with `service resticprofile... start` ... blocking until service is finished). This isn't really a requirement for backup services, I think.

**Comment by creativeprojects** [comment]
Hi,

I honestly can't remember why I've chosen `oneshot` when I was looking at systemd implementation. I think there was something funny when working with timers. I'll investigate a bit more, but at first glance it looks like `simple` is indeed more suited.

What's the problem you're having with the lock files though? I do use them and it works fine for me. But I should look into it if it doesn't work properly.

Thanks 😄

**Comment by jkellerer** [comment]
Hi @creativeprojects , thanks a lot for the quick reply and the quick look into service types.

Regarding the other topic: 
Lock files causes a failure when a process is already running and abort a new start. That is mostly what one wants except when multiple things are scheduled for the same repo / lock file and should run, just not concurrently. I'm monitoring syslogs and I don't want to see failures when they aren't real failures. 

With my schedules "hourly" (backup) and "daily" (check/forget) on the same repo/lock file this breaks, since all scheduled services start in the same second.

I'm not yet sure whether there should be an option to wait for locks (that's what I currently do using a pre-script and my own locks) or whether my schedules should be different (likely also a thing). So I've not yet articulated a feature request (or PR), I need to collect more experience first.

**Comment by creativeprojects** [comment]
Thanks for the explanation @jkellerer 

This is now fixed in v0.10.1 👍🏻
