### ISSUE TITLE
Please provide a build time option to disable self-update

### ISSUE THREAD

**Issue by darix** [creativeprojects/resticprofile#170]
for packagers it would be helpful if we could turn off the self update. restic itself solves that via a [tag](https://github.com/restic/restic/blob/master/build.go#L59). maybe a similar solution could be applied here?

**Comment by creativeprojects** [comment]
yes you can use build tags in go, although it's quite limited (include or exclude a whole file basically)
I'll have a look

**Comment by gedw99** [comment]
+1 would be nice if a simple build tag can be used to remove the self update.

your self update tool is really great btw @creativeprojects
