### ISSUE TITLE
Ansible playbook link is dead

### ISSUE THREAD

**Issue by Gaibhne** [creativeprojects/resticprofile#173]
In the documentation on https://creativeprojects.github.io/resticprofile/installation/ansible/index.html an Ansible playbook is linked, but leads to a 404 error. The problem is that the link is wrong:

Actual link:
https://creativeprojects.github.io/resticprofile/files/resticprofile.yml

Correct link:
https://creativeprojects.github.io/resticprofile/installation/ansible/files/resticprofile.yml

**Comment by creativeprojects** [comment]
Thanks for the information 👍🏻 

I'll update the documentation now 😉

**Comment by Gaibhne** [comment]
Thanks!
