### ISSUE TITLE
Darwin background process type 

### ISSUE THREAD

**Issue by EkilDeew** [creativeprojects/resticprofile#18]
On Mac OS, the niceness does not really change the behavior of a process. However there's a key in a Launchd plist file that set the process type. For exemple if the process type is set to `Background` the OS will throttle the process in order to not trigger the fans for exemple.
It would be nice to add this key when setting the priority for a profile.

This can be found here : https://www.unix.com/man-page/OSX/5/launchd.plist/.

I do understand that this may be a problem because resticprofile sets the niceness when triggering the process rather than in the Launchd plist file itself.

**Comment by creativeprojects** [comment]
Like you mentioned it's only going to work on a scheduled task, but not when started from the command line.
If it's what you need, yes I can add the parameter to the launchd file.

**Comment by EkilDeew** [comment]
I can add it myself, do not trouble yourself with too much work :) 
I forgot to say thanks for what you've done its amazing !

The goal is indeed to set the process type to Background when started from a scheduled task and keep the normal process type when started from command line. Should I open a PR ?

**Comment by creativeprojects** [comment]
> Should I open a PR ?

Sure 👍🏻

**Comment by creativeprojects** [comment]
Fixed by https://github.com/creativeprojects/resticprofile/pull/19
