### ISSUE TITLE
Potential data race with status.json

### ISSUE THREAD

**Issue by damoclark** [creativeprojects/resticprofile#186]
https://github.com/creativeprojects/resticprofile/blob/7ba20ad91a2b35af456534b090fdbaaee95accb6/monitor/status/progress.go#L71

I've been investigating an unusual outcome from my backups and forgets where I know for sure that the forget is running successfully (from stdout+stderr output with timestamps from RP), but the status.json file is not being updated with the timestamp that the forget ran.  There are concurrent RP activities running at the same time on this host.  This has occurred 3 days in a row, and then the status.json finally updated appropriately this morning.  I noticed that the timing and order of my backups on that host were different to those previously.  

My immediate thoughts turned to a data race in RP where multiple RP instances load the status.json update it, and then save it back.  I did some digging around in the code, and despite my very limited knowledge of Go, it appears that there are no locking semantics used when updating the shared status.json file.  

But in my mind, it is dubious that this potential data race is the culprit for my issues.  This is because the window within which the data race can occur in RP is very small (as shown above) and for it to happen multiple times in a row seems highly unlikely. 

But I thought I would report this anyway.  You know, Murphy's Law and all that. :) 

I'll monitor what happens with my backups going forward and collect more data to see if I can pin-point the issue.

I do wish to say that the status-file feature of Resticprofile is brilliant!  I nearly started engineering something myself to do something similar until I found this little gem.  Very well done. :)

Damien.

**Comment by creativeprojects** [comment]
Hi!

Thanks for your message :)

Like you mentioned, the `getGenerator()` function loads the content of the status file. The next line updates the current job then saves it immediately. At most the whole process should take a few milliseconds (which can be verified by running the tests in `status_test.go`)

That would be **very** unlikely that a race condition would prevent the status file from being written.

Would you mind posting your configuration to get a better understanding of what is running concurrently?

**Comment by damoclark** [comment]
> Would you mind posting your configuration to get a better understanding of what is running concurrently?

Sure, I'll send it through tonight. 

> At most the whole process should take a few milliseconds (which can be verified by running the tests in status_test.go)
> That would be very unlikely that a race condition would prevent the status file from being written.

Unless there is IO contention on the host, which is quite likely during backups.  With spinning disks, memory pressure and/or virtualisation environments, processes can be blocked, sometimes for seconds.  Execution time is unpredictable in time-sharing systems. 

But I understand that you have to weigh additional complexity/maintainability in the code with determinism of execution.  Which of course is entirely your call. :)  It's easy for me to say, when I don't have to do the work. ;) 

D.

**Comment by damoclark** [comment]
My issue is definitely not a race condition.  The log entries timestamps for different tasks don't overlap.  

I've solved the mystery, and it is operator error.  I manually ran a forget command with RP using a different profile which has left a latent retention status.  It just happens to be the first one, and I didn't scan through the remainder of the json (unformatted) to notice the actual profile in use.

I already created a 'bare' profile which does not include the status-file option.  Just need to remember to use it. :)

**Comment by creativeprojects** [comment]
Classic 😆 

I usually have a base profile and a schedule profile; something like that:

```yaml
one-profile:
    repository: local:/backup

one-profile-schedule:
    inherit: one-profile
    status-file: status.json
    backup:
        source: /
        schedule: "daily"
```

On the command line, it's easier to remember to use the base name of the profile 👍🏻

**Comment by damoclark** [comment]
Great tip Fred.  Thanks! :)
