### ISSUE TITLE
Shortcut to home folder `~` seems broken in v0.21.0

### ISSUE THREAD

**Issue by creativeprojects** [creativeprojects/resticprofile#187]
I have one machine using a repository on a `~/backup` folder which stopped working after `v0.21.0`.

Needs more investigation

**Comment by creativeprojects** [comment]
Same with en variables (`$HOME`)

**Comment by creativeprojects** [comment]
It's coming from the change in the way the flags are generated:
from `--repo path` to `--repo=path`

It looks like the shell cannot expand values after a `=`?

```
% restic snapshots --repo=~/backup --password-file examples/key
Fatal: unable to open config file: stat ~/backup/config: no such file or directory
Is there a repository at the following location?
~/backup

% restic snapshots --repo ~/backup --password-file examples/key
Fatal: unable to open config file: stat /Users/CP/backup/config: no such file or directory
Is there a repository at the following location?
/Users/CP/backup
```

**Comment by jkellerer** [comment]
Looks like the shell doesn't resolve variables after an equals sign.
Was reported here: https://github.com/spf13/cobra/issues/1765
