### ISSUE TITLE
[Question] How to configure forget with empty keep-tag

### ISSUE THREAD

**Issue by MorphBonehunter** [creativeprojects/resticprofile#194]
Usually i do not tag my backups.
So tags on snapshots have an special meaning and should be keep forever.
Restic implents this with an empty `--keep-tag ''` (see the info section under [remove snapshots docu](https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy)),
this also applies to the `--tag` paramter (further down in the docu).

I can not get this to work with resticprofile.
My naive approach was to use `keep-tag: "''"` but this ends in generating `--keep-tag=\'\'` and restic shows `Applying Policy: ... and all snapshots with tags [['']]` and doesn't work.

So maybe someone could help me with this?

**Comment by jkellerer** [comment]
At the moment, there is no way to specify empty tags in a profile.
This can be considered a bug that needs fixing.

**Comment by akronym0** [comment]
I also ran into this bug. +1
