### ISSUE TITLE
Cannot schedule jobs on Windows with schedule-permission `user_logged_on`

### ISSUE THREAD

**Issue by rsnitsch** [creativeprojects/resticprofile#199]
The option

    schedule-permission: user_logged_on

does not work on my Windows host. The following error appears when I run `resticprofile schedule --all`:

    error creating job profilename/backup: error creating \resticprofile backup\profilename backup task: Ausnahmefehler aufgetreten. ((28,8):UserId:)

"Ausnahmefehler aufgetreten" translates to "Exceptional error occurred".

Note: I switched from `user_logged_on` to `user`, which works. This suggests there is a specific problem with `user_logged_on`.

My system:

    Windows 11 Pro
    resticprofile version 0.21.1 commit b6a98ef85477b3ec49c5aac027142c89e1b4d9ab

**Comment by creativeprojects** [comment]
The feature was developed on Windows 10.
It might be that something is a bit different with Windows 11.
I no longer have a window laptop so I'll spin up a new VM and try on it.

Thanks for this report 👍🏻

**Comment by creativeprojects** [comment]
Right, so I was able to schedule tasks with `schedule-permission: user_logged_on`

Edition	Windows 11 Pro
Version	21H2
Installed on	‎27/‎01/‎2023
OS build	22000.1817
Experience	Windows Feature Experience Pack 1000.22000.1817.0

Could it be that your user is not allowed to run background tasks? is it an isolated windows machine or is it part of a windows domain? (typically a computer managed by your company)

**Comment by rsnitsch** [comment]
My Windows machine is managed all by myself.

What do you mean by "not allowed to run background tasks"? I mean, with the `user` option it _does_ work, so in principle I can schedule background tasks. Where do I find such a setting? I asked GPT-4 and it proposed the following policy could be related:

1. Press Win + R to open the Run dialog box, then type gpedit.msc and press Enter to open the Local Group Policy Editor.
2. Navigate to the following path in the Local Group Policy Editor:
    Computer Configuration -> Windows Settings -> Security Settings -> Local Policies -> User Rights Assignment
3. In the right pane, locate and double-click on the policy setting called "Log on as a batch job."

However, after I added my user account to that policy, it still does not work. The same (useless) error message appears. It's frustrating as hell that Windows does not produce meaningful error messages in many cases.

Anyway, for now I can work with the `user` setting, so it's not urgent.

**Comment by creativeprojects** [comment]
I'll be doing an upgrade of the library to access the task scheduler in Windows #206 
That might fix your problem, or eventually send a more specific error message 🤞🏻

**Comment by creativeprojects** [comment]
Can you try if the latest version `0.22.0` fixed your problem?

**Comment by rsnitsch** [comment]
> Can you try if the latest version `0.22.0` fixed your problem?

It did not fix the problem, but the error message is more specific now:

    2023/05/13 17:49:46 error creating job profilename/backup: error creating registered task \resticprofile backup\profilename backup: error registering task: No mapping between account names and security IDs was done.

**Comment by jkellerer** [comment]
Hi @rsnitsch, the error sounds like a problem with the Windows user profile. If you ask a search engine for "No mapping between account names and security IDs was done" there are several explanations how this can be fixed, mostly involving:
* Get the current username
* Fix the username in ProfileImagePath in the registry

Since I'm not a Windows user and don't know if the proposed fixes really help, I don't want to give any advices. Also you can easily create more damage than fixing something so be careful with this.

Maybe you can still check (but not change anything) if this might apply to your system. E.g. if  ProfileImagePath contains the incorrect username.

**Comment by rsnitsch** [comment]
Yup, this is some weird Windows issue it seems. I did not find a fix that works for me. If I manage to fix this later on, I'll add a comment. But for now I'll close this issue because it is not resticprofile's fault...

Thank you all for your support.
