### ISSUE TITLE
No notification if scheduler failed

### ISSUE THREAD

**Issue by renard** [creativeprojects/resticprofile#20]
On Unix like systems, cron is able to send a mail (using `MAILTO` variable). `systemd` doesn't.

However this can be bone by the use of `OnFailure` option as described here: https://northernlightlabs.se/2014-07-05/systemd-status-mail-on-unit-failure.html

Not sure similar actions can be done with `launchd` or under Windows though.

This would be useful is the task scheduler could notify (or run a script) is `resticprofile` fails to start for some reason.

**Comment by jkellerer** [comment]
Hi @renard ,

You can achieve the same with `resticprofile` since it has `run-after-fail`.

E.g. in `profiles.yaml` you set:

```yaml
default: 
  ...
  run-after-fail: 
    - 'resticprofile-send-error name@domain.tl'
```

With `/usr/local/bin/resticprofile-send-error` being:

```sh
#!/usr/bin/env bash
[[ -z "${PROFILE_NAME}" ]] || sendmail -t <<ERRMAIL
To: $1
From: "Resticprofile $(hostname -f)" <$USER@$(hostname -f)>
Subject: Restic Failed: ${PROFILE_COMMAND} "${PROFILE_NAME}"
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8

${ERROR}

---- 
DETAILS:

$(systemctl status --full "resticprofile-${PROFILE_COMMAND}@profile-${PROFILE_NAME}")
ERRMAIL
exit 0
```

**Comment by jkellerer** [comment]
@creativeprojects , I was wondering whether it would make sense to provide such scripts in a `contrib` section.

**Comment by renard** [comment]
@jkellerer Unfortunately you can't mainly because this assumes:

* that `resticprofile` could start (ie configuration file is not OK, this is a human error and can happen frequently, we don't know 😉)
* and that the *systemd scheduler* works nicely. I won't troll *systemd* that why I introduce #21 as an alternative suggestion for users who prefer *cron* over *systemd*.

**Comment by jkellerer** [comment]
@renard , thanks for your update. I do agree that using `run-after-fail` has limits. Also when considering dynamic config generation with template variables, one can easily create invalid configs at runtime that appear to be valid at first.

So yes I also think it does make sense to allow configuring `OnFailure` separately.

**Comment by creativeprojects** [comment]
> @creativeprojects , I was wondering whether it would make sense to provide such scripts in a `contrib` section.

Actually this is a very good idea.

The way I solve this problem on my servers is via the [status file](https://github.com/creativeprojects/resticprofile#status-file-for-easy-monitoring): I have a script that feeds the last time the backup has finished into a zabbix instance. This way I know pretty quickly that something didn't run. This is a script I can share as well

**Comment by jkellerer** [comment]
Status file is a nice option as well. 

I think the requirements how to best integrate monitoring are different that’s why it makes sense to have multiple options. 

Adding a separate ‘run-on-failure’ for schedules has a very valid use case since it doesn’t depend on resticprofile to get triggered.

**Comment by creativeprojects** [comment]
I kept this issue opened because I wanted to find a nice way of dealing with it, and not forcing the user to adopt only one way of doing it.

How about adding the possibility of defining your own unit files via a go template?
This way anybody can add any kind of monitoring/notification they want in their systemd service.

**Comment by jkellerer** [comment]
Was also thinking about "run-on-failure" and there is one thing that would make this directive different from all others: "environment". All existing "run-..." actions in are triggered by resticprofile in a configurable environment. But this wouldn't be the case when the scheduler executes the action directly (of course it could be handled to some extent but that would make things unnecessarily complex).

Using a template should be a good option to customise scheduling and add this feature (and possible others). While this is then a bit more complex to configure, it is more consistent and flexible.
