### ISSUE TITLE
Neither `--verbose`, `--trace` nor `--dry-run` display the actual restic commands

### ISSUE THREAD

**Issue by rsnitsch** [creativeprojects/resticprofile#201]
I would like to check how resticprofile actually executes restic, i.e. the full commandline including all parameters. I expected this to be easy, because in my mind it is the most natural thing to do when switching to resticprofile: You test it first by experimenting with the options until you can reliably reproduce your previous setup.

First I tried running resticprofile with `--verbose`, but that does not print the restic commandline. `--trace` doesn't work either. In general I noticed that neither of these options seems to affect the output much (or at all).

The option `--dry-run` _does_ affect the send-after webhook command (it doesn't get executed but instead a debug message appears). However, the restic commandlines still are not printed. At least it seems that this `--dry-run` flag is passed to `restic backup` and `restic forget`, because I noticed that no snapshots are actually added and the retention policy does not get executed (`restic forget` just prints "Would have removed the following snapshots" etc.).

It seems like a bug when considering this:

      --dry-run              display the restic commands instead of running them
      (...)
      --trace                display even more debugging information
      -v, --verbose          display some debugging information

The description of `--dry-run` explicitly states that the restic commands should not get executed, but instead be displayed.

It's also suspicious that neither `--verbose` nor `--trace` affect my output much (or at all, but I haven't checked each line).

My system:

    Windows 11 Pro
    resticprofile version 0.21.1 commit b6a98ef85477b3ec49c5aac027142c89e1b4d9ab

**Comment by creativeprojects** [comment]
There is something wrong here, as the `verbose` flag **do** print the command line about to be executed.
If used with `dry-run` you will actually see the command displayed twice.

Here's an example (on a Linux VPS) with the command `snapshots` in dry-run mode where you can see the command twice (for verbose and dry-run)
<img width="1158" alt="Screenshot 2023-04-23 at 13 41 27" src="https://user-images.githubusercontent.com/24314560/233840481-d24995d7-1d83-4e1a-ab66-5dcccf88c7fa.png">

**Comment by Gaibhne** [comment]
You didn't put your command line, so I can only guess: did you possibly not pay close attention to the `resticprofile` syntax and wrote something along the lines of `resticprofile backup --dry-run` ? From the output of `--help`:

`resticprofile [resticprofile flags] [profile name.]restic-command [restic flags]`

Note that `resticprofile`'s `--dry-run` comes BEFORE the `restic` command. Arguments after the command will be passed to `restic` instead. `--dry-run works as expected for me:

```
C:\restic>resticprofile.exe --dry-run key list
2023/04/23 14:42:07 using configuration file: profiles.yaml
2023/04/23 14:42:08 profile 'default': starting 'key'
2023/04/23 14:42:08 dry-run: C:\Users\me\AppData\Local\Microsoft\WinGet\Packages\restic.restic_Microsoft.Winget.Source_...\restic_0.15.1_windows_amd64.exe key --exclude-caches --one-file-system --password-file=restic.creds --repo=rest:http:,,, list
2023/04/23 14:42:08 profile 'default': finished 'key'
```

**Comment by rsnitsch** [comment]
@Gaibhne You're absolutely correct. Indeed I put the flags for resticprofile at the end, so they got passed on to restic. My bad...

Thank you for your quick replies.
