### ISSUE TITLE
Unable to create Windows Task schedule with permission `system`

### ISSUE THREAD

**Issue by Gaibhne** [creativeprojects/resticprofile#205]
Either variation (install from elevated prompt, install from user prompt and click yes) results in a task that, upon first running, will report something like 'request was denied' for a split second (too fast for me to memorize completely) followed by a generic 'Access is denied 0x80070005'. I am the sole super user on my machine, not in a domain or anything like that. Running the backup manually works perfectly fine with no errors or warnings. Copying the parameters from the task and running resticprofile manually from an elevated shell works with no errors or warnings.

I want a whole disk backup, so I definitely need permission `system`.

**Comment by creativeprojects** [comment]
Is the `resticprofile` binary on the local disk, or would it be available from a network drive?
