### ISSUE TITLE
Add cron support

### ISSUE THREAD

**Issue by renard** [creativeprojects/resticprofile#21]
Some people prefer having a cron managed backup system. It would be nice if resticprofile could generate this cron task.

**Comment by creativeprojects** [comment]
I think that could be quite easy to do 👍🏻

**Comment by creativeprojects** [comment]
Support added in https://github.com/creativeprojects/resticprofile/commit/b8c3e6a0c785ef3254d7d35465ebf913f5538b42

I've tested it on different flavours of Debian (and Debian based like Ubuntu). It *should* work on other distributions but I haven't tested.

Let me know if it works for you 👍🏻
