### ISSUE TITLE
Allow to schedule "prune"

### ISSUE THREAD

**Issue by jkellerer** [creativeprojects/resticprofile#22]
This is a request to add `prune` to the list of `ScheduledSections`.

At the moment `check`, `backup` and `retention` can be scheduled. However one of the heaviest tasks, `prune` is not available. While retention can do `prune` as well it isn't very practical for large repositories (e.g. in my case, it runs +1 hour for a 500G repo on ordinary HDDs). 

While retention policies can differ per path and tag, `prune` should just be run once per-repo (and at a lower rate). A separate schedule option would allow to configure this easily.

**Comment by jkellerer** [comment]
Btw. I'm open to provide this as a PR if that is fine.

**Comment by creativeprojects** [comment]
Sure, go ahead of you're happy to 👍🏻 it should be very similar to the `check` one
