### ISSUE TITLE
empty group-by option doesn't work

### ISSUE THREAD

**Issue by mkatsevVR** [creativeprojects/resticprofile#232]
If I set `group-by: ""` as documentation recommends to disable grouping and then run `resticprofile -v forget`, the `--group-by` argument is not passed to restic at all. If I use any non-empty value it works as expected

**Comment by jkellerer** [comment]
@mkatsevVR, this issue should be fixed when resticprofile 0.23 is released (`group-by: ""` is supported then).

**Comment by mkatsevVR** [comment]
thanks
any idea when that would be?

**Comment by creativeprojects** [comment]
Actually I was preparing a release when restic was released. So I delayed it to include the new restic 0.16 options.

I have a couple of MR to review and I think it could be out of the door this week or the next one 👍🏻
