### ISSUE TITLE
Compile instructions are missing dependencies, at least eget and mockery.

### ISSUE THREAD

**Issue by AphidGit** [creativeprojects/resticprofile#233]
On a freshly installed linux system, running; 

`zypper install -y go git make makeinfo autoconf automake gcc gcc-c++`

Then trying to compile by hand: 

```
git clone https://github.com/creativeprojects/resticprofile.git 
cd resticprofile 
make build 
```
results in: 
```
generate.go:4: running "eget": exec: "eget": executable file not found in $PATH
config/info.go:20: running "mockery": exec: "mockery": executable file not found in $PATH
```
The instructions at https://creativeprojects.github.io/resticprofile/installation/source/index.html are out of date, there appear to be some undocumented dependencies. 

Edit: These commands appear to do the trick: 

``` 
go install github.com/zyedidia/eget@latest
PATH=$PATH:~/go/bin
```

**Comment by jkellerer** [comment]
@AphidGit , would you mind trying https://github.com/jkellerer/resticprofile/tree/fix-mockery-warning (PR #234)?
