### ISSUE TITLE
You made me laugh. I appreciate that. That is all. Have an excellent day.

### ISSUE THREAD

**Issue by ethereal-engineer** [creativeprojects/resticprofile#254]
>But you can also define variables yourself. Hand-made variables starts with a $ ([PHP](https://en.wikipedia.org/wiki/PHP) anyone?) and get declared and assigned with the := operator ([Pascal](https://en.wikipedia.org/wiki/Pascal_%28programming_language%29) anyone?). Here’s an example:

I'm ancient enough to have programmed in both of these, and this gave me a good chuckle. Thank you.

**Comment by creativeprojects** [comment]
😆 
As a matter of fact, Pascal was the very first language I learned as a kid.
And funny enough my first internship/job was in Delphi. Yeah I'm getting old 😞

**Comment by ethereal-engineer** [comment]
OMG me too!! (Well the first language I learnt as a kid was BASIC but my first REAL coding job was in Delphi (if you exclude a PAINFUL stint in RPG400) - it took me a decade to exit the Delphi programming sphere. Experience in demand I guess. As basic as that language was. It was such a relief to ditch the primitive BEGIN END syntax.

**Comment by creativeprojects** [comment]
That first job was rewriting a MS Access `vba` app in Delphi, so it was actually feeling very advanced 🤣

**Comment by ethereal-engineer** [comment]
Oh god. MS Abscess. Haven't heard that one in a long time.

**Comment by ethereal-engineer** [comment]
Happy to report I have just converted my restic backup script of several years, stain from db dumps, files, innumerable excludes and edge cases, and multiple machines and repos, into a profiles.yaml and it is running so seamlessly that even all the parent snapshots are being picked up and used properly. The effort that has gone into this is understated. I look forward to optimising my backup system now. 😁

**Comment by creativeprojects** [comment]
Nice to hear 👍🏻 happy to help 😊
