### ISSUE TITLE
systemd After=network-online.target

### ISSUE THREAD

**Issue by thorpelawrence** [creativeprojects/resticprofile#257]
Hi, thanks for your work on this project. I wondered if you considered an option for requiring a network connection, before running a section, for example I've noticed on first boot, sometimes my timer triggers before network is online (even on ethernet), causing my webhooks to fail. Usually this is not a problem as the backup completes, and the success HTTP hook sends, but it would be nice to have the full picture (start to end) on e.g. healthchecks.io.

I could do this using a custom systemd timer template and adding the following (from https://systemd.io/NETWORK_ONLINE/)

```diff
+[Unit]
+After=network-online.target
```

However, I would not automatically get the upstream changes to the template, if any.

I suppose one thing to consider is if there is no internet and HTTP hooks are the _only_ form of notification, you would obviously miss out on that failure. (Though, I suppose you would notice your network is down, anyway.)

**Comment by thorpelawrence** [comment]
If this is something you would consider, I would be happy to contribute. I just wanted to check first if I missed anything or if it was decided against.

**Comment by creativeprojects** [comment]
Hi!

Yeah I suppose it doesn't hurt to add it to the default template.

Would `network-online` be enough? I was looking at the apt-daily on my Debian VM and I can see a lot more (although some of these services don't even exist):

```
[Unit]
Description=Daily apt download activities
Documentation=man:apt(8)
ConditionACPower=true
After=network.target network-online.target systemd-networkd.service NetworkManager.service connman.service

[Service]
Type=oneshot
ExecStartPre=-/usr/lib/apt/apt-helper wait-online
ExecStart=/usr/lib/apt/apt.systemd.daily update
```

In the meantime, if you want more control over systemd, you can change both service and timer templates globally: https://creativeprojects.github.io/resticprofile/schedules/systemd/index.html#how-to-change-the-default-systemd-unit-and-timer-file-using-a-template

**Comment by thorpelawrence** [comment]
From another look, I saw a few services do it using the `.service` rather than the `.timer`, e.g. https://gitlab.archlinux.org/archlinux/archlinux-keyring/-/blob/ba43b79aea3e8c0c7113e61f1d9409d8b2da77e4/wkd_sync/archlinux-keyring-wkd-sync.service.in#L7

One I found also has both `Wants=` and `After=`, but I would guess one is ok.

```
[Unit]
Description=Refresh Pacman mirrorlist with Reflector.
Documentation=https://wiki.archlinux.org/index.php/Reflector
Wants=network-online.target
After=network-online.target nss-lookup.target
```

**Comment by thorpelawrence** [comment]
I found some more discussion on the https://systemd.io/NETWORK_ONLINE/ around e.g. `NetworkManager` (presumably for WiFi etc). Though it does mention the best thing is to handle failures gracefully.

I wonder if another, possibly better thing to consider is to have some kind of (auto-)retry functionality in the HTTP hooks?

**Comment by creativeprojects** [comment]
>  I saw a few services do it using the .service rather than the .timer

Yes it's better in the service

> I wonder if another, possibly better thing to consider is to have some kind of (auto-)retry functionality in the HTTP hooks?

Yes that's also possible. Good idea.

**Comment by thorpelawrence** [comment]
Thanks, I can have a look at implementing both possibly, I was considering adding some functionality to create an [drop-in/override file](https://wiki.archlinux.org/title/systemd#Drop-in_files) for systemd, (`systemctl edit`), which so far I've been doing manually for e.g. env vars and [encrypted secrets](https://systemd.io/CREDENTIALS/). Might be a more generic solution to editing the templates directly and allow those that want to put their own `After=` as well, for example.
