### ISSUE TITLE
add `latest: N` in copy command or allow to pass additionals commands / filter as a whole for scheduler ...

### ISSUE THREAD

**Issue by thiscantbeserious** [creativeprojects/resticprofile#263]
**What I want to achieve:** 

Don't copy ALL snapshots just the latest one (with or without tag/host filters).

Use case is basically for disaster recovery you only want to copy the latest snapshot onto a storage that is append-only.

This more or less seen from a longer-term perspective.

However this should be also important for any cloud provider like b2 or aws - where you only want to store a bare minimum of data for cost reasons, without looking at if it's append-only or not.

**Description of the issue:** 

You currently cannot limit the number of snapshots with the copy command when used in the scheduler.

On the command line however simply doing 

`resticprofile [myprofile].copy latest` 

will do the trick to copy the latest snapshot - since this exact same behaviour is possible with restic copy - as mentioned in the the docs here:

https://restic.readthedocs.io/en/latest/045_working_with_repos.html#copying-snapshots-between-repositories

so basically it will unfold to:

`restic copy --host abc --tag mytag1,mytag2 latest`

**Possible implementation:**

snapshots section already has a `latest: N` and it works well if I specify `latest:1` and then do `resticprofile [myprofile].snapshots` on commandline e.g.

... but maybe it might be better to simply giving the option to forward the filter in the scheduler like:

`scheduler-command: latest e6392582 c2571162`

or is this already possible in any way?

**Current workaround:**

I basically run `resticprofile schedule --all` with crond and then modify it with `crontab -e` and add **latest** 

before:

`00 03 01 * *    cd /root/ && /usr/bin/resticprofile --no-ansi --config /root/.config/resticprofile/profiles.yaml --name documents copy`

after:

`00 03 01 * *    cd /root/ && /usr/bin/resticprofile --no-ansi --config /root/.config/resticprofile/profiles.yaml --name documents copy latest`

**Comment by creativeprojects** [comment]
Hi!

Thanks for the detailed report.

This is definitely a miss in the `copy` command.

I think the best is to introduce a `snapshot` option in the `copy` section.

**Comment by thiscantbeserious** [comment]
many thanks! will try it out and give feedback
