### ISSUE TITLE
Not able to select CodeBlock in Docs.

### ISSUE THREAD

**Issue by KAGEYAM4** [creativeprojects/resticprofile#269]
[Profile Inheritance Docs](https://creativeprojects.github.io/resticprofile/configuration/inheritance/index.html#profile-inheritance)

![image](https://github.com/creativeprojects/resticprofile/assets/75798544/86d5001d-0e46-4098-aa2b-dcf080ca223c)

Not able to switch to these sections.

**Comment by jkellerer** [comment]
Thanks a lot for the report. This got broken after that last template update. @creativeprojects , as far as I can remember the new template needed a tweak for the tabs, maybe those 2 are missing the updates?

**Comment by creativeprojects** [comment]
I'm not sure if that was the issue but I noticed a few of the shortcodes closing with a `{{% /tabs %}}` instead of a `{{< /tabs >}}`

Annoyingly I can't push the docs without releasing a new version. I think I'm going to move the documentation from GitHub.io

**Comment by creativeprojects** [comment]
@KAGEYAM4 does it work for you? https://271-merge.resticprofile.pages.dev/configuration/inheritance/

**Comment by KAGEYAM4** [comment]
> @KAGEYAM4 does it work for you? [271-merge.resticprofile.pages.dev/configuration/inheritance](https://271-merge.resticprofile.pages.dev/configuration/inheritance/)

yes its working now.
