### ISSUE TITLE
[Suggestion] Add --profile as an alias to --name

### ISSUE THREAD

**Issue by xpufx** [creativeprojects/resticprofile#287]
I get why it's 'name'. The tool itself is called so and so profile. But it sounds more descriptive with 'profile' I think. (Bit more discoverable too). Especially since within profiles.yaml each section is referred mostly as a profile regardless of the binary's name. An alias would be more than enough to cover this if it makes sense for people.

**Comment by creativeprojects** [comment]
Yes, we can easily add an alias 😉 

BTW there's also another syntax you might like: `<profile>.<command>`.

Like:
```
resticprofile root_profile.backup
```

**Comment by jkellerer** [comment]
@creativeprojects , it might make sense to support `backup.profile` also. With command completion I often first think of the task (e.g. backup) and then of the profile. Would be good if either order is supported.

**Comment by creativeprojects** [comment]
Yeah I agree. I started to use `<command>@<profile>` for the `run-schedule` command, which is not something the user would see anyway, but we could also accept it.
