### ISSUE TITLE
feature request: run-after-fail (and other run- directives) only for scheduled tasks

### ISSUE THREAD

**Issue by dpantel** [creativeprojects/resticprofile#292]
Hello

Just started using this project, and it's a really nice wrapper for restic.

I am currently scheduling restic tasks and logging results to a file. I wanted to ability to send an email alert on error. So after browsing the documentation, I added a script to email myself in the `run-after-fail` section of my profile. Great!

Here is where I have an issue. I was playing around with resticprofile and tagging snapshots etc etc etc. Because I don't know the command line syntax very well, I generated a lot of errors. Lo and behold, my inbox was full of them.

What I would like is an error email sent _only_ for unattended scheduled tasks, not for errors I can plainly see on the console when I am using resticprofile manually. I would like to request an additional set of `run-` directives that apply only to scheduled tasks, i.e. `schedule-run-after-fail`, etc.

I know this was discussed in #20, which resulted in templates for systemd in #75. Unfortunately, I don't see how that solves my issue. Even if I create a template for a resticprofile unit, which has a `OnFailure=` directive, I will then have to manually create and install not only the "mailer" script, but also a systemd unit that calls that script.

**Comment by creativeprojects** [comment]
There's an easy way of fixing this issue simply by using profile inheritance.
- You create a base profile that you use for manual commands
- You create a second profile that inherits from the base one, with the scheduling commands added to it.

```yaml

profile:
  backup:
    source: /

scheduled_profile:
  inherit: profile
  run-after-fail: email_me
  backup:
    schedule: daily
```

This is a very basic example but that should give an idea 👍🏻

**Comment by creativeprojects** [comment]
> Even if I create a template for a resticprofile unit, which has a OnFailure= directive, I will then have to manually create and install not only the "mailer" script, but also a systemd unit that calls that script.

As for this other issue, there's a new feature coming in v0.25.0 that allow you to extend the resticprofile systemd service file with your own rules.

https://6d459fd5.resticprofile.pages.dev/schedules/systemd/#systemd-drop-in-files

**Comment by dpantel** [comment]
That's a neat way around it, and the new systemd features look cool too. Thank!
