### ISSUE TITLE
Profile `show` leaves out some information.

### ISSUE THREAD

**Issue by dpantel** [creativeprojects/resticprofile#293]
When viewing a profile with `show` command, some parameters are left out of the output. Namely, I have noticed the following are missing:

```
backup: check-before, check-after
retention: after-backup, before-backup
```

**Comment by creativeprojects** [comment]
You're right, there's a bug that prevent the display of `after-backup` and `before-backup`.

But actually `check-before` and `check-after` are working (unless you specify a value of `false` in which case they keep their default value and are not shown)
