### ISSUE TITLE
SFTP schedule fails but manual trigger succeeds

### ISSUE THREAD

**Issue by Eamourinho** [creativeprojects/resticprofile#294]
I'm a bit at a loss here, I'm connecting through SFTP, I think the issue is that it's not passing my RSA key, as it works when I run "resticprofile backup" after adding my ssh key to the current session, however scheduling the task fails as it doesn't load the ssh key. Is this something that can be configured? I can't find anything relating to "rsa" or "ssh" in the docs.

**Comment by creativeprojects** [comment]
One possible reason is that the schedule is using a different user: are you scheduling with the option `schedule-permission` set to `system`? in which case it's going to use the default RSA key from the `root` user.

**Comment by Eamourinho** [comment]
I am schedule-permission set to system and using the root user has an rsa key configured... The RSA key is password restricted though, should I generate one without a password? Is that secure? <_<

**Comment by creativeprojects** [comment]
Yeah, during the schedule the key cannot work without entering the passphrase in that case 😉 
You don't really have a choice but remove the passphrase from the key.

You should create a SFTP user only, and don't use this account to login to the machine (the account/key is only used for restic backups)

**Comment by Eamourinho** [comment]
Okay that worked! Awesome thank you so much for that help, amazing tool and I'm so excited to start leveraging it just about everywhere :D
