### ISSUE TITLE
RFE: Don't require specifying repository in a profile's configuration

### ISSUE THREAD

**Issue by tjanez** [creativeprojects/resticprofile#3]
Hi!

First of all, thanks for creating and maintaining this wonderful tool that makes configuring restic a breeze!

In my setup, I usually use an environment file to set (i.e. source) certain environment variables, namely `B2_ACCOUND_ID`, `B2_ACCOUNT_KEY`, `RESTIC_REPOSITORY` and `RESTIC_PASSWORD`.

Currently, the following check https://github.com/creativeprojects/resticprofile/blob/fc8468d68f5b36109b559b4c7f32a8391fdf6668/src/resticprofile/main.py#L114-L117 prevents resticprofile from accepting a profile configuration without the repository key specifyied, even though one is set via `RESTIC_REPOSITORY` environment variable.

Could we skip this check or check if the `RETIC_REPOSITORY`is set as an environment variable?

**Comment by creativeprojects** [comment]
Hi,

Yes, I suppose we could check the environment variable is set

**Comment by tjanez** [comment]
> Yes, I suppose we could check the environment variable is set

Yes, that would be great.

**Comment by creativeprojects** [comment]
v0.5.2

**Comment by tjanez** [comment]
Great, thanks!
