### ISSUE TITLE
Set password manually 

### ISSUE THREAD

**Issue by SpoonCreator** [creativeprojects/resticprofile#300]
Hi
I took a long time, but I still haven't found a way to enter the password manually (by typing in the console), without using a password file. 
Is there such a possibility? Or perhaps a workaround.
Thanks

**Comment by jkellerer** [comment]
hi @SpoonCreator , it looks that this is not possible at the moment as `restic` is not connected with stdin. If it would, you'd need to enter the password multiple times though (for every call to restic).

If resticprofile would collect a password on the other hand it would still need to use an (access restricted) temp file or some other sort of method to transfer the PW that is not necessarily safer and as using a custom wrapper around `resticprofile` that is doing this.

E.g. a wrapper script could look like this:

```shell
#!/bin/sh

# temp password file
export RESTIC_PASSWORD_FILE="$(mktemp)"
# protect file
chmod 0600 "$RESTIC_PASSWORD_FILE"
# delete file on exit
trap "rm '$RESTIC_PASSWORD_FILE'" exit

# ask for password
echo "Enter Password:"
read -s pass && echo -n "$pass" > "$RESTIC_PASSWORD_FILE"

# run resticprofile
resticprofile "$@"
rp_code=$?

# overwrite password file with "*" (prior to delete)
printf %100s | tr " " "*" > "$RESTIC_PASSWORD_FILE"

# forward exit code
exit $rp_code
```

**Comment by creativeprojects** [comment]
The idea of resticprofile is to automate the whole process.
Sorry it would be too complicated to introduce such a feature 😢
