### ISSUE TITLE
Restic version in docker image is quite old

### ISSUE THREAD

**Issue by OrbitingOcelot** [creativeprojects/resticprofile#308]
Hi,
I like the idea of resticprofile, and would like to use the docker-based version for my nas backups.
Unfortunately, I found out that the bundled restic version 0.16.0 is quite old, and contains some critical bugs which can even lead to data loss.
Would it be possible to periodically refresh the container image, or maybe even rebuild it automatically on restic minor releases?
Thank you :)

**Comment by creativeprojects** [comment]
For now the docker image is rebuilt on each release of resticprofile, but that's true we don't have any other pipeline to rebuild the docker image outside of a release 😞 

I'll see if I can push a release and find another way of creating a docker image.

**Comment by creativeprojects** [comment]
Closing for now as of https://github.com/creativeprojects/resticprofile/releases/tag/v0.25.0

**Comment by OrbitingOcelot** [comment]
Wow awesome, thank you so much for the quick release! 🤩

**Comment by creativeprojects** [comment]
FYI I'm also trying out a weekly rebuild of the docker image: #309 
This way we would also automatically get any security patch on the base image (alpine Linux)

**Comment by OrbitingOcelot** [comment]
Oh nice, that would be a really useful improvement! I love that your single container gives me all tools I need for my nas backup, no compose messing around required! :)
