### ISSUE TITLE
Environment variables from file

### ISSUE THREAD

**Issue by mjmeintjes** [creativeprojects/resticprofile#316]
I'd like to get the sensitive environment variables (like S3 keys) from a file instead of having them directly in the config file.

So similar to the `password-file` option, maybe have an `env-file` in addition to the current `env` option.

**Comment by creativeprojects** [comment]
Yeah I suppose that shouldn't be difficult to implement 🤔

**Comment by jkellerer** [comment]
@creativeprojects , I'll take this one.

**Comment by jkellerer** [comment]
... and for later maybe: re-evaluate profile if env changed.
