### ISSUE TITLE
Cannot load configuration file: cannot open configuration file for reading: open profiles.yaml on MacOS

### ISSUE THREAD

**Issue by kamil-rudnicki** [creativeprojects/resticprofile#330]
I get this error `2024/02/25 11:12:55 cannot load configuration file: cannot open configuration file for reading: open profiles.yaml: operation not permitted` when run automatically using scheduler.

- MacOS
- Tried to give 777 to profiles.yaml

**Comment by creativeprojects** [comment]
Hey,

I need a bit more information than that. It could be so many things.

As a starting point, can you post your configuration file (with any repository information redacted) so we can see how your schedule is configured?

**Comment by creativeprojects** [comment]
Closing as not enough information.
You can re-open if needed 👍🏻
