### ISSUE TITLE
check the age of the last backup

### ISSUE THREAD

**Issue by kalos** [creativeprojects/resticprofile#35]
I think it's a good idea to implement a check of the age of the last backup
like [rester](https://github.com/fgma/rester) does.

Thank you

**Comment by creativeprojects** [comment]
Hi,

resticprofile has a slightly different approach: it can produce a [status file](https://github.com/creativeprojects/resticprofile#status-file-for-easy-monitoring) after running the main restic commands (backup, check, forget)

How would you like this feature to work instead?

**Comment by kalos** [comment]
Ah!
My fault, I didn't read that part of documentation.

It seems to me a more flexible approach
Thank you!
