### ISSUE TITLE
Load config from ~/.config/resticprofile on MacOS too

### ISSUE THREAD

**Issue by elkowar** [creativeprojects/resticprofile#369]
While I know that ~/.config is _technically_ not as standardized on MacOS as it is on Linux via the XDG-basedir specs, it is still a de facto standard place to put configuration files. It would be neat if resticprofile would start loading the profiles from ~/.config/resticprofile on MacOS the same way it does on linux just for the sake of consistency, and for the sake of potentially helping people that re-use some scripting or configuration across several systems, that version-control their .config (not that it necessarily makes sense to share a resticprofile config across computers, but there might be other tools that look at the config or interface with it in some way that benefit from it being in a standard location).

**Comment by creativeprojects** [comment]
I was just checking on my mac, and as it turns out I do have a few configs in the `~/.config` folder indeed. Although a lot less than the standard `~/Library/Application Support`.

I suppose it doesn't hurt to add it to the list 😉
