### ISSUE TITLE
Populate a variable from command execution

### ISSUE THREAD

**Issue by WebSpider** [creativeprojects/resticprofile#373]
Is it possible to use command executions to populate a variable in resticprofile?

Example:

The application I want to backup uses user-configurable storage paths, and I want to back them up as I perform application backups, so I need to ask the application to give me a list of locations where it has stored stuff.

`curl https://my.app/api/v1/storage-locations` gives me back a list with storage locations, and I'd like to use that to populate the `sources` directive.

I've found ways to assign variables directly, and I've found ways to reference environment variables, so I *could* write a wrapper around `resticprofile` to first get the stuff I need, store it in the environment and then call `resticprofile`, but this seems counter-intuitive.

Is there any other way that I can do this natively?

**Comment by creativeprojects** [comment]
Hey!

Actually you can already do that with a feature waiting to be released:

https://github.com/creativeprojects/resticprofile/pull/323

Would that work for you?

You can try to compile resticprofile from the main branch if you want to test it out.

I guess a new release is overdue 😆

**Comment by creativeprojects** [comment]
version `0.27.0` is out 👍🏻

**Comment by WebSpider** [comment]
Awesome, that works for me! :rocket:
