### ISSUE TITLE
nixos packaging support

### ISSUE THREAD

**Issue by sigmonsays** [creativeprojects/resticprofile#376]
I would like to use this tool on nixos.

anyone else interested in using resticprofile on nix?

**Comment by sigmonsays** [comment]
FYI, Just found that it's pending https://github.com/NixOS/nixpkgs/pull/306589

**Comment by creativeprojects** [comment]
I'm not using NixOS myself so I'm not sure I can be of much help here.

Trying Nix packages on macOS is on my list of things to do though 🤔

**Comment by sigmonsays** [comment]
we can close this out for now, it's already underway. This issue should probably be tracked in nixpkgs.

If you wanted to put a note in the readme that would be nice though =P
