### ISSUE TITLE
Move "Reference" to the end of section 2 [Docs]

### ISSUE THREAD

**Issue by W1zzardTPU** [creativeprojects/resticprofile#380]
Took me a while of searching to find "Reference". 

It's probably better to always keep it at the end of section 2, or maybe put it into its own top-level section? Maybe before Contributions?

**Comment by creativeprojects** [comment]
🤔 
Moving it to its own section would make sense.
With possibly a page for each sub-section.

This page is auto-generated from the code so we need to update the generator for that though.

Thanks for the hint 😉
