### ISSUE TITLE
Feature request: add support of Restic 0.17 option `--insecure-no-password`

### ISSUE THREAD

**Issue by Vanav** [creativeprojects/resticprofile#391]
Restic 0.17 option `--insecure-no-password` allows to create backups without encryption, that is useful for local or trusted repository. [Implement `--insecure-no-password` option. by MichaelEischer · Pull Request #4808 · restic/restic](https://github.com/restic/restic/pull/4808)

**Comment by creativeprojects** [comment]
Should be covered by https://github.com/creativeprojects/resticprofile/pull/350
