### ISSUE TITLE
Retention and logic with keep-tag

### ISSUE THREAD

**Issue by rzbrk** [creativeprojects/resticprofile#4]
First of all, thank you very much for resticprofile, which makes using restic so much easier!

restic itself distinguishes between the following two commands (taken from https://restic.readthedocs.io/en/latest/060_forget.html):

The following command removes all but the last snapshot of all snapshots that have either the "foo" or "bar" tag set:
    restic forget --tag foo --tag bar --keep-last 1

The following command keeps the last snapshot of all snapshots with both the tag "foo" and "bar" set:
    restic forget --tag foo,bar --keep-last 1

How is it possible to distinguish both above restic commands with keep-tag in resticprofile? I found out, that resticprofile doesn't accept more than one line "keep-tag".

Thank you very much,
rzbrk

**Comment by creativeprojects** [comment]
Hi,

In the first case, you can put each tag in a list
```toml
tag = [ "foor", "bar" ]
```

and for the second case, you can put the tags inside the same value
```toml
tag = [ "foor, bar" ]
```

or even

```toml
tag = "foor, bar"
```

I haven't tried just now but I reckon that should work :)

**Comment by rzbrk** [comment]
Thank you very much for your answer! I had the chance to check it only recently and can confirm the behaviour described above.

keep-tag = [ "foo", "bar" ] keeps all snapshots with tags "foo" or "bar" or both.
keep-tag = [ "foo, bar" ] keeps all snapshots with both tags "foo" and "bar".

Thank you very much for clarification.
