### ISSUE TITLE
`continue-on-error` broken since `0.26.0`

### ISSUE THREAD

**Issue by Cryszon** [creativeprojects/resticprofile#406]
I updated my old version of `resticprofile` and `continue-on-error` no longer seems to be working.

## `0.25.0` and earlier
```
...
Warning: at least one source file could not be read
2024/09/30 13:12:22 backup on profile 'user-data': exit status 3
2024/09/30 13:12:22 profile 'spaces': starting 'backup'
open repository
...
```

## `0.26.0` and later
```
...
Warning: at least one source file could not be read
2024/09/30 13:10:28 backup on profile 'user-data': exit status 3

$ 
```

**Comment by creativeprojects** [comment]
That's right I can see the issue is there: https://github.com/creativeprojects/resticprofile/compare/v0.25.0...v0.26.0#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R430

We should start adding integration tests on groups 😞

**Comment by creativeprojects** [comment]
While a fix is being released, in the meantime you can use the global flag:

```yaml
global:
    group-continue-on-error: true
```
