### ISSUE TITLE
BUG: retention section is not inherited

### ISSUE THREAD

**Issue by Milamber07** [creativeprojects/resticprofile#424]
Hello,
I use one profile section to provide backup, retention and check parameters to all other profiles.
Hence all other profiles has an inherit line for below section.

```
[mac-generic]

  [mac-generic.backup]
    compression = "max"
    no-error-on-warning = true
    exclude-caches = true
    one-file-system = false
    check-before = false
    check-after = false
    host = "mac"
    read-concurrency = 10
  
  [mac-generic.retention]
    before-backup = false
    after-backup = false
    keep-hourly = 12
    keep-daily = 14
    keep-weekly = 5
    keep-monthly = 6
    keep-within = "12h"
    keep-tag = [ "forever" ]
    prune = true
  
  [mac-generic.check]
    read-data-subset = "15%"
    with-cache = false
```

For some reason using forget command for inherited retention gives an error.
```
~ resticprofile mac-hdd-docs.forget
Fatal: no policy was specified, no snapshots will be removed
```

1-2 weeks ago forget worked fine. Update seems to be the issue.

Meanwhile using backup or check commands work as intended.

resticprofile 0.28.1 commit 249fd41b3d8e1af034594c9617bc3145a6a3e29a
restic 0.17.1
Mac OS 14.7

**Comment by xuhuanzy** [comment]
It seems that `retention` is not working.

```
PS E:\backup> resticprofile workspace-all.retention
...
unknown command "retention" for "restic"
```

**Comment by creativeprojects** [comment]
Hey

It's probably not very clear, but `retention` and `forget` are very different:
- `retention` cannot be called separately, it is only calling the `forget` command after a backup, with the configuration from the `retention` section
- `forget` section is the configuration of the `forget` command (not as part of a backup)

My original idea is that you could have a separate configuration for _automatic_ forget (`retention`) and a _manual_ forget. I think this wasn't a great idea after all, as it is quite confusing.

So, for the
```
resticprofile mac-hdd-docs.forget
```
command to work, you need to copy the `retention` section to a `forget` section.

**Comment by Milamber07** [comment]
Hey!
Yep, renaming solves everything. Thanks!

P.S. I was under impression forget can use retention section since several weeks ago I did start it with forget command... and everything worked fine. Anyway, the issue has been resolved.
