### ISSUE TITLE
run-after/before in forget command

### ISSUE THREAD

**Issue by WMP** [creativeprojects/resticprofile#43]
Hello, i need `run-after` and `run-before` in forget ccommand, because i want to clone my repository with rclone, like as described in this post: https://forum.restic.net/t/ransomware-check/2795/2

**Comment by creativeprojects** [comment]
I suppose I could.
But as I understand the post, I think you can use the `run-after` a `backup`.
I would rclone the repository after every backup.

**Comment by WMP** [comment]
Yes, you have right, i will try in this way.
