### ISSUE TITLE
Homebrew Tap

### ISSUE THREAD

**Issue by thde** [creativeprojects/resticprofile#44]
Heya, I tried to create a Formula for Homebrew, but sadly the project is not popular enough (yet):
https://github.com/Homebrew/homebrew-core/pull/75432

As GoReleaser allows maintaining a Tap, would you consider to add this to the CI config?
https://goreleaser.com/customization/homebrew/

**Comment by thde** [comment]
I could try to create a PR if this is something you'd consider :).

**Comment by creativeprojects** [comment]
> As GoReleaser allows maintaining a Tap, would you consider to add this to the CI config?

Yes, that's something on my TODO list (along with Linux packages).

I'm not using Homebrew myself but I'll give it a go 👍🏻

**Comment by creativeprojects** [comment]
So I've created the repository `homebrew-tap` instead, I might push some other stuff in there at some point.
I tried with an Intel Mac and it worked 😄 

`$ brew tap creativeprojects/tap`
`$ brew install resticprofile`

I'll try from Linux as well and update the documentation 👍🏻 

Thanks for your help

**Comment by thde** [comment]
Great. Thanks!
