### ISSUE TITLE
Bug: restic-binary not being honored

### ISSUE THREAD

**Issue by Syphdias** [creativeprojects/resticprofile#51]
I set `restic-binary` in `global` to `"~restic/bin/restic"`.

`resticprofile -n <profile> show` shows it set correctly while `backup` (and other commands) show `/usr/bin/restic`.
But `resticprofile -n <profile> --dry-run backup` shows the regular path `/usr/bin/restic`.

It also runs the wrong binary.

**Comment by Syphdias** [comment]
For context why I even need this: [I don't run my backups as root.](https://restic.readthedocs.io/en/latest/080_examples.html#full-backup-without-root)

**Comment by creativeprojects** [comment]
Good point. I haven't had a look at it yet but it could be the "~" not working everywhere. As a matter of fact I only ever used the option on Windows.

**Comment by Syphdias** [comment]
I think – was a bit late for me – I tried the whole path (`/home/restic/bin/restic`) as well but only as dry run.

**Comment by creativeprojects** [comment]
I was able to replicate the bug with a `~` but not with a full path 👍🏻

**Comment by Syphdias** [comment]
Am I doing this wrong? I created a mi
```
❯ resticprofile version
resticprofile version 0.14.0 commit "6ec5177df4086a021fa068cb9ae8f28804f768b3"

❯ cat /tmp/profiles.toml
[global]
restic-binary = "/home/restic/bin/restic"

[default]

❯ resticprofile -c /tmp/profiles.toml show
global:
    default-command:          snapshots
    restic-binary:            /home/restic/bin/restic
    restic-lock-retry-after:  1m0s
    restic-stale-lock-age:    2h0m0s
    min-memory:               100

default:


❯ resticprofile -c /tmp/profiles.toml --dry-run
2021/06/21 20:01:51 profile 'default': starting 'snapshots'
2021/06/21 20:01:51 dry-run: /usr/bin/restic snapshots
2021/06/21 20:01:51 profile 'default': finished 'snapshots'
```

**Comment by creativeprojects** [comment]
That is weird 🤔 is the file `/home/restic/bin/restic` readable?

**Comment by Syphdias** [comment]
> That is weird  is the file `/home/restic/bin/restic` readable?

No, for my current user neither `~restic/bin/` nor `~restic/bin/restic` have `r` or `x` permission.

Hm, can I use `sudo -u restic ~restic/bin/restic` as a "binary"? I assume it would try `'sudo -u restic' backup`...

**Comment by creativeprojects** [comment]
> No, for my current user neither `~restic/bin/` nor `~restic/bin/restic` have `r` or `x` permission.

Ok that explains it, resticprofile was trying to find a suitable candidate since it couldn't access the binary. I guess I should display a warning or something.

> Hm, can I use `sudo -u restic ~restic/bin/restic` as a "binary"? I assume it would try `'sudo -u restic' backup`...

You can run resticprofile under the same user and that should work (all child processes will inherit the user):

`sudo -u restic resticprofile backup`

**Comment by Syphdias** [comment]
> `sudo -u restic resticprofile backup`

Until now I had the resticprofile binary not installed for all user which is why I even ran into this because the binary wasn't accessible to the user `restic` :wink:

**Comment by Syphdias** [comment]
I can confirm that version 0.14.1 fixes both issues regarding no permissions and `~` path.
