### ISSUE TITLE
[FEATURE REQ] Option to use Windows VSS for backup

### ISSUE THREAD

**Issue by alexj-m** [creativeprojects/resticprofile#6]
Hi there,

Firstly thanks for the great project - this is exactly what Restic needs and has made my life so much easier!!! Love it!!

I'm backing up both Windows and Linux systems using Resticprofile and on Windows it would be really handy if it was possible to use the Windows Volume Shadow Copy Service (VSS) as an option prior to backing up to make a shadow copy of the files to backed up.

On Windows lot of files in the Users home directory are in use (think email mailboxes etc) at the time the backup is run and without the use of VSS Restic can not access the files.

Do you think this would be a feature you'd be willing to consider for Resticprofile?

**Comment by creativeprojects** [comment]
Yes that's something I could look into.
I'm mostly using resticprofile for linux and mac, but I can try it on my windows machine at work.
It might take a while if it involves writing powershell scripts though :smile:

**Comment by alexj-m** [comment]
That would be amazing!!

Unfortunately I don't know any Go (and I feel your pain with powershell :-)), but I was thinking that these two Go libraries could make it reasonably simple:

https://github.com/mholt/wmi
https://github.com/function61/varasto/tree/master/pkg/fssnapshot

But as I said I don't know anything about Go to even know if they are useful or not.

**Comment by creativeprojects** [comment]
Well, actually it looks like there's already an implementation of it that is _possibly_ ready to be merged:
https://github.com/restic/restic/pull/2274/

I could definitely implement something similar inside resticprofile if it doesn't get merged soon.

**Comment by alexj-m** [comment]
Brilliant, thanks for that, I'll take a look.

**Comment by azurefreecovid** [comment]
> 
> 
> Well, actually it looks like there's already an implementation of it that is _possibly_ ready to be merged:
> [restic/restic#2274](https://github.com/restic/restic/pull/2274)
> 
> I could definitely implement something similar inside resticprofile if it doesn't get merged soon.

Thanks for linking this issue, you've saved me a real headache. I've been using Resticprofile (love it btw, so thanks a lot!!) and trying to find a VSS solution for Windows as well, some how I missed the PR myself.

**Comment by creativeprojects** [comment]
VSS was merged in restic code, I can close it
