### ISSUE TITLE
Self update gives an error

### ISSUE THREAD

**Issue by azurefreecovid** [creativeprojects/resticprofile#7]
Hi there,

Thanks for the great project!! It is really useful.

Not sure if it is just me, but the self update function is giving me an error on Windows:

```sh
PS C:\resticprofile> .\resticprofile.exe --self-update
2020/06/25 14:30:46 resticprofile 0.6.1 compiled with go1.14.2
Do you want to update to0.7.0? (y/n): y
2020/06/25 14:30:48 Invalid input
```

No great drama as I can easily update manually, but I just thought I'd let you know.

**Comment by azurefreecovid** [comment]
Never mind, looking at the latest release info I'm guessing you fixed this one.

Sorry about that, should have caught that before I posted.

**Comment by creativeprojects** [comment]
You were right, there was a problem self-updating under Windows. Sorry I don't test stuff often enough on Windows sadly.
Please note the bug will still be there the **next time** you update obviously since the version 0.7.0 still has the bug :face_with_head_bandage:

**Comment by azurefreecovid** [comment]
No worries at all!
