### ISSUE TITLE
docs: setcap (read-only `/`, root-like) setup

### ISSUE THREAD

**Issue by jtagcat** [creativeprojects/resticprofile#78]
Continuation from https://github.com/restic/restic/issues/2408 and [restic/docs/examples#backing_up_system_without_running_restic_as_root](https://restic.readthedocs.io/en/latest/080_examples.html#backing-up-your-system-without-running-restic-as-root)

It'd be nice if there was a similar example with resticprofile.

noping edit: I can /assign self, but due date I can promise would be 2022q2

**Comment by creativeprojects** [comment]
that's because I'm not using this setup. But I can try on one server and document it

**Comment by creativeprojects** [comment]
@jtagcat have you ever managed to get it working?

I was trying today, but then I realised that the code apparently has to elevate itself to the required capability: it's not transparent for the program.

(I'm referring to this article in particular: https://sites.google.com/site/fullycapable/getting-started-with-go/building-go-programs-that-manipulate-capabilities)

**Comment by jtagcat** [comment]
I have nothing to comment, I don't use resticprofile at the moment. Feel free to close.
