### ISSUE TITLE
Struggling to get command to work

### ISSUE THREAD

**Issue by DarrenPIngram** [creativeprojects/resticprofile#82]
_This is not a bug, but probably a bug in the head of the user._

I am trying to get Resticprofile to run. I can run Restic itself, using the following (I note the "transfers" bit has no actual benefit, but hadn't changed it pending a move to Resticprofile. (system is MacOS 10.15.7, installed via your "brew" instructions.

This is how (so far) I have run Restic in various tests.

```
restic -o rclone.program="/usr/local/bin/rclone" \
  -o rclone.args="serve restic --stdio --transfers 10 --verbose" \
  -r rclone:DR:restic/Appdata backup /Volumes/Appdata
```
I have configured this in Resticprofiles (DR is the Dropbox mount, configured through rclone, e.g.` restic -r rclone:foo:bar init`
```
di@MacPro .restic % resticprofile profiles
2021/10/27 13:41:28 using configuration file: profiles.conf

Profiles available (name, sections, description):
  appdata:   (n/a)  
  default:   (env)  
  no-cache:  (n/a)  
```
I can see the data by entering `rclone ls DR:restic/Appdata`

But if I launch Resticprofiles it brings up an error,  and despite looking extensively at your notes I am struggling to see what I have done wrong.

I am trying to launch Resticprofiles by resticprofile -n appdata backup

Could someone look at it? Also if any other errors are noticed I welcome being corrected, as I continue my journey. The objective of this job is to backup /Volumes/Appdata to DR:restic/Appdata each time it is run. I will worry about scheduling later.

In /Users/di/.restic I have the following files

```
-rw-r--r--  1 di  staff    64 Oct 27 11:21 exclude.txt
-rw-r--r--  1 di  staff    14 Oct 27 11:22 password.txt
-rw-r--r--  1 di  staff  2394 Oct 27 13:51 profiles.conf
```

profiles.conf : pastebin https://pastebin.com/6QtexdF0

**The objective would be to have different backup locations (DR=Dropbox, GD=Google Drive (both via rclone) with different volumes getting different repositories, e.g. DR:restic/Vol2, DR:restic/Vol3 and each Vol would get its own section in square brackets as I have done with Appdata**

Thank you in advance for any guidance!

**Comment by creativeprojects** [comment]
> I do have some other questions and no doubt more in the future, is it OK to
post as new "issues" (even though they are not necessarily bugs), or do you
have a different preferred venue?

You can also use the [Discussions](https://github.com/creativeprojects/resticprofile/discussions) for that matter

> One feature request, unless it is always possible and I've not figured it
out, is the ability to run the profile with another job (in another tab)
whilst one backup is running (e.g. to two or more separate backup jobs).

If your backup target is different you can already do that.
If the backup target is the same I would probably not want to do that.
