### ISSUE TITLE
Unable to open repo clone error?

### ISSUE THREAD

**Issue by DarrenPIngram** [creativeprojects/resticprofile#83]
Something seems to have broken my (ongoing) development of backups.

I added logging to the rclone commands and went to test everything but it errors out. I've not found anything helpful I could troubleshoot with. May I trouble you for some guidance:

```
di@MacPro .restic % resticprofile --name appdata backup          
2021/10/29 09:25:07 using configuration file: profiles.conf
2021/10/29 09:25:07 profile 'appdata': starting 'backup'
open repository
Fatal: unable to open repo at rclone:DR:restic/Appdata: error talking HTTP to rclone: Get "http://localhost/file-5577006791947779410": unexpected EOF
2021/10/29 09:25:08 backup on profile 'appdata': exit status 1
```

First, here was the changes but I can't see how they could be responsible (extract only from the profiles.conf)

```
[appdata]
repository = "rclone:DR:restic/Appdata"
option = [

    "rclone.program=/usr/local/bin/rclone",

    "rclone.args=serve restic --stdio --verbose **--log-file=/users/di/.restic/Appdata-log.txt --log-level NOTICE**"

]

```
Yet, at least, rclone seems to be working if I query it via the command line.
```
di@MacPro .restic % rclone lsd DR:restic/Appdata
          -1 2021-10-29 09:25:29        -1 data
          -1 2021-10-29 09:25:29        -1 index
          -1 2021-10-29 09:25:29        -1 keys
          -1 2021-10-29 09:25:29        -1 locks
          -1 2021-10-29 09:25:29        -1 snapshots
```
What I don't understand is the _talking to http_ stuff, but I've not set up anything different (default installation) and the machine has not been rebooted since it was working.

d

**Comment by creativeprojects** [comment]
I think I know what's happening:

As I tried a very similar configuration as yours, I got this in the `Appdata-log.txt` file:

```
$ cat Appdata-log.txt
2021/10/29 20:04:55 Can't set -v and --log-level
2021/10/29 20:04:55 Can't set -v and --log-level
2021/10/29 20:05:09 Can't set -v and --log-level
2021/10/29 20:05:09 Can't set -v and --log-level
```

Also I think you have mistyped your home folder, if you're on a Mac it's probably `/Users/di/.restic/Appdata-log.txt` (with uppercase **U**)

**Comment by DarrenPIngram** [comment]
Thank you kindly for the extra information and picking up the typographical
error (red face).

D

‌
