### ISSUE TITLE
Backup fails, but status file says it succeeded

### ISSUE THREAD

**Issue by butwhoscounting** [creativeprojects/resticprofile#88]
_I'm not sure whether this is a bug or if I'm simply missing something obvious myself._

I usually run resticprofile with the following command:
`/usr/local/bin/resticprofile --log /home/resticapp/restic_backup.log -c /home/resticapp/backup.toml -n samba backup`

Due to some file permissions issues on my system the backups have recently been failing and the aforementioned command has been exiting with an exit status of "1". This failure is also logged in **restic_backup.log** (albeit with a different exit status):
> error: Open: open /home/samba: permission denied
> Files:           0 new,     0 changed, 233235 unmodified
> Dirs:            0 new,     0 changed, 17701 unmodified
> Data Blobs:      0 new
> Tree Blobs:      0 new
> Added to the repo: 0 B  
> 
> processed 233235 files, 1.054 TiB in 0:33
> snapshot 421e6af4 saved
> Warning: at least one source file could not be read
> 2022/01/30 16:10:05 ERROR backup on profile 'samba': exit status 3

However, for some reason the **backup-status file** says that the backup has succeeded:
> {
>   "profiles": {
>     "samba": {
>       "backup": {
>         "success": true,
>         "time": "2022-01-30T16:10:05.167367547+02:00",
>         "error": "",
>         "stderr": "error: Open: open /home/samba: permission denied\nWarning: at least one source file could not be read\n",
>         "duration": 35,
>       } } } }

_(I've omitted some lines from here to make it shorter.)_

Since the log shows that the backup failed I would have expected the status file to reflect this as well with `"success": false` instead of `"success": true`.

If anybody could provide some insight as to why this happens it would be much appreciated. I'm trying to monitor my backups with Zabbix, but not being able to rely on the `success` value being accurate throws a monkey wrench into my plans.

I'm using restic v0.12.1 and resticprofile v0.16.0.

**Comment by jkellerer** [comment]
Have you set `no-error-on-warning: true`? ([#warnings-from-restic](https://github.com/creativeprojects/resticprofile#warnings-from-restic))

**Comment by butwhoscounting** [comment]
Thanks for fast response! I hadn't configured the `no-error-on-warning` option at all, but I now added it to my config, first setting the value to `false` (which as I understand is what I need and also the default) and then out of curiosity to `true`. Unfortunately when running the backup the end result was the same either way.

Here's the full config with the newly added line:

> [global]
> min-memory = 300
> 
> [default]
> repository = "rest:https://[REDACTED]"
> password-file = "[REDACTED]"
> status-file = "/home/resticapp/backup-status.json"
> initialize = false
> 
> [samba]
> inherit = "default"
> initialize = true
> 
> [samba.backup]
> verbose = true
> source = [ "/home/samba" ]
> exclude-caches = true
> no-error-on-warning = false

**Comment by jkellerer** [comment]
Thanks for the update. In that case it might be a bug in `resticprofile` since return code from `restic` is "3" and that is what the `no-error-on-warning` option also checks for (when deciding to set the end result to success or failure).

**Comment by butwhoscounting** [comment]
Is there any additional diagnostic info I could provide that would make troubleshooting this issue easier?

When I manually check the exit status with `echo $?` after running resticprofile it tells me that it exited with the status of `1`.

**Comment by jkellerer** [comment]
From the logs (and exit code 1) it looks that `resticprofile` detects the error correctly however the status file contains success where it should not be. If more info is required I'll let you know, at the moment it seems this is enough.

**Comment by creativeprojects** [comment]
I don't know if you had time to have a look, but I found the issue. I can prepare a fix 👍🏻

**Comment by jkellerer** [comment]
Had started but you‘ve been faster :)

**Comment by creativeprojects** [comment]
It should be fixed in [v.0.16.1](https://github.com/creativeprojects/resticprofile/releases/tag/v0.16.1) 👍🏻
