### ISSUE TITLE
Crash - No definition for backup command in this profile

### ISSUE THREAD

**Issue by tj57** [creativeprojects/resticprofile#91]
` test2:
    initialize: false
    repository: e:\\restic_test2\
    password-command: nc 192.168.2.1 2900
 
    copy:
        initialize: false
        repository: e:\\restic_test2_copy\
        password-command2: nc 192.168.2.1 2900`

`d:\prg\restic>resticprofile.exe -n test2 backup
2022/02/14 21:10:21 using configuration file: profiles.yaml
2022/02/14 21:10:21 profile 'test2': starting 'backup'
2022/02/14 21:10:21 No definition for backup command in this profile

===============================================================
uh-oh! resticprofile crashed miserably :-(
Can you please open an issue on github including these details:
===============================================================
   os:         windows
   arch:       amd64
   version:    0.16.1
   commit:     358f060c7b8ced0f2e95effe7dce3588dcc5c8a0
   compiled:   2022-01-30T19:52:48Z
   by:         goreleaser
   error:      runtime error: invalid memory address or nil pointer dereference
   stack:      goroutine 1 [running]:
runtime/debug.Stack()
   /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/debug/stack.go:24 +0x65
main.showPanicData()
   /home/runner/work/resticprofile/resticprofile/main.go:410 +0x4aa
panic({0x10f5d60, 0x1766c50})
   /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/panic.go:1047 +0x266
main.(*resticWrapper).runCommand(0xc000312210, {0xc0000180f0, 0xc000125625})
   /home/runner/work/resticprofile/resticprofile/wrapper.go:318 +0x1c9
main.(*resticWrapper).runProfile.func1.1()
   /home/runner/work/resticprofile/resticprofile/wrapper.go:158 +0x15e
main.runOnFailure(0xa9d38d, 0xc0001256a0, 0xc000125690)
   /home/runner/work/resticprofile/resticprofile/wrapper.go:768 +0x7f
main.(*resticWrapper).runProfile.func1(0x0)
   /home/runner/work/resticprofile/resticprofile/wrapper.go:111 +0x8f
main.lockRun({0x0, 0xc0003a50f0}, 0x1, 0x0, 0xc000125868)
   /home/runner/work/resticprofile/resticprofile/wrapper.go:670 +0x215
main.(*resticWrapper).runProfile(0xc000312210)
   /home/runner/work/resticprofile/resticprofile/wrapper.go:109 +0xba
main.runProfile(0xac90e0, 0xc0003120b0, {0x0, 0x0, 0x0, 0x0, {0x11d064c, 0x8}, {0x0, 0x0}, ...}, ...)
   /home/runner/work/resticprofile/resticprofile/main.go:367 +0x6c9
main.main()
   /home/runner/work/resticprofile/resticprofile/main.go:219 +0x10fc

===============================================================`

**Comment by creativeprojects** [comment]
Do you have a status file, or prometheus activated in your profile?

Otherwise I can't replicate it, although I can see exactly why it happens.

**Comment by tj57** [comment]
Ok, I will try to replicate it with status file.

**Comment by tj57** [comment]
I got crash again, here is scenario:

`test3-copy:
    initialize: false
    repository: rest:http://yogi:8010/test3_copy
    password-command: nc 192.168.2.1 2900

test3:
    initialize: false
    repository: rest:http://yogi:8010/test3
    password-command: nc 192.168.2.1 2900
    prometheus-push: "http://yogi:8020/"
    prometheus-save-to-file: "prometeus-test3" 
 
    copy:
        initialize: false
        repository: rest:http://yogi:8010/test3_copy
        password-command2: nc 192.168.2.1 2900
    backup:
       source: 
       - c:\tmp\restic_test1\
       tag:
       - test2
       exclude:
       - "/**/.git/"
       - "/*.zip"
       - "*.bin"
    status-file: "backup-status-test3.json"`

1. with this config file run commands
2. resticprofile.exe -v -n test3 init
2. resticprofile.exe -v -n test3-copy init
3. resticprofile.exe -v -n test3 backup
4. resticprofile.exe -v -n test3 copy
5. comment out all backup yaml section in test3
6. resticprofile.exe -v -n test3 backup
7. got crash
[restic_log.zip](https://github.com/creativeprojects/resticprofile/files/8067596/restic_log.zip)

**Comment by creativeprojects** [comment]
Yes, this one I can reproduce: It should be fixed by https://github.com/creativeprojects/resticprofile/commit/fe336ffdc690995366fc6e29cec1c79320ebc591

Thanks for reporting the defect 👍🏻

**Comment by tj57** [comment]
Thank you for this usefull tool.
